import { ICartListing } from "../types";

export const calculateCartTotal  = (_cart: ICartListing)=>{
    if(process.env.NODE_ENV === 'development'){
        _cart = {
            "id": 136,
            "note": "",
            "created_at": "2023-04-19T21:51:56.002Z",
            "updated_at": "2023-04-19T21:51:56.002Z",
            "line_items": [
                {
                    "id": 1,
                    "cart_id": 136,
                    "product_id": 1,
                    "variant_id": 5,
                    "variant_option_id": 3,
                    "quantity": 2,
                    "product": {
                        "id": 1,
                        "title": "HomePod",
                        "published_at": null,
                        "tags": "music, electronics",
                        "metafields_global_title_tag": "",
                        "metafields_global_description_tag": "",
                        "seo_description": "",
                        "seo_title": "",
                        "created_at": "2023-04-11T12:48:48.020Z",
                        "updated_at": "2023-04-11T12:48:48.020Z",
                        "status": "active",
                        "images": [
                            {
                                "id": 1,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219466084",
                                "updated_at": "1681219466084",
                                "variant_ids": [
                                    5
                                ],
                            },
                            {
                                "id": 2,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219647379",
                                "updated_at": "1681219647379",
                                "variant_ids": [],
                            },
                            {
                                "id": 3,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151541",
                                "updated_at": "1681220151541",
                                "variant_ids": [],
                            },
                            {
                                "id": 4,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151792",
                                "updated_at": "1681220151792",
                                "variant_ids": [],
                            },
                            {
                                "id": 5,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220235065",
                                "updated_at": "1681220235065",
                                "variant_ids": [],
                            },
                            {
                                "id": 6,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220314556",
                                "updated_at": "1681220314556",
                                "variant_ids": [],
                            },
                            {
                                "id": 7,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220640410",
                                "updated_at": "1681220640410",
                                "variant_ids": [],
                            },
                            {
                                "id": 8,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220661777",
                                "updated_at": "1681220661777",
                                "variant_ids": [],
                            },
                            {
                                "id": 9,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220712222",
                                "updated_at": "1681220712222",
                                "variant_ids": [],
                            },
                            {
                                "id": 10,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221193876",
                                "updated_at": "1681221193876",
                                "variant_ids": [],
                            },
                            {
                                "id": 11,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221219918",
                                "updated_at": "1681221219918",
                                "variant_ids": [],
                            },
                            {
                                "id": 12,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221294025",
                                "updated_at": "1681221294025",
                                "variant_ids": [],
                            },
                            {
                                "id": 13,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221300756",
                                "updated_at": "1681221300756",
                                "variant_ids": [],
                            },
                            {
                                "id": 14,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221455559",
                                "updated_at": "1681221455559",
                                "variant_ids": [],
                            },
                            {
                                "id": 16,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221525855",
                                "updated_at": "1681221525855",
                                "variant_ids": [],
                            }
                        ],
                        "image": {
                            "id": 1,
                            "product_id": 1,
                            "is_default": true,
                            "position": 1,
                            "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                            "width": 2820,
                            "height": 2400,
                            "alt": "",
                            "created_at": "1681219466084",
                            "updated_at": "1681219466084",
                        },
                        "variants": [
                            {
                                "id": 5,
                                "product_id": 1,
                                "image_id": 1,
                                "position": 1,
                                "price": 99,
                                "compare_at_price": 99,
                                "grams": 0,
                                "requires_shipping": true,
                                "sku": "SKU#LF83UERR",
                                "title": "color",
                                "created_at": "1681390906000",
                                "updated_at": "1681390906000",
                                "weight": 0,
                                "weight_unit": "gram",
                                "options": [
                                    {
                                        "id": 3,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                    },
                                    {
                                        "id": 4,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                    }
                                ],
                                "__typename": "ProductVariant"
                            }
                        ],
                        "shipping_rate": {
                            "id": 1,
                            "product_id": 1,
                            "title": "Standart shipping",
                            "price": 0,
                            "compare_at_price": 0,
                        },
                        "__typename": "Product"
                    },
                    "__typename": "CartLine"
                },
                {
                    "id": 2,
                    "cart_id": 136,
                    "product_id": 1,
                    "variant_id": 5,
                    "variant_option_id": 3,
                    "quantity": 1,
                    "product": {
                        "id": 1,
                        "title": "HomePod",
                        "published_at": null,
                        "tags": "music, electronics",
                        "metafields_global_title_tag": "",
                        "metafields_global_description_tag": "",
                        "seo_description": "",
                        "seo_title": "",
                        "created_at": "2023-04-11T12:48:48.020Z",
                        "updated_at": "2023-04-11T12:48:48.020Z",
                        "status": "active",
                        "images": [
                            {
                                "id": 1,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219466084",
                                "updated_at": "1681219466084",
                                "variant_ids": [
                                    5
                                ],
                            },
                            {
                                "id": 2,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219647379",
                                "updated_at": "1681219647379",
                                "variant_ids": [],
                            },
                            {
                                "id": 3,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151541",
                                "updated_at": "1681220151541",
                                "variant_ids": [],
                            },
                            {
                                "id": 4,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151792",
                                "updated_at": "1681220151792",
                                "variant_ids": [],
                            },
                            {
                                "id": 5,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220235065",
                                "updated_at": "1681220235065",
                                "variant_ids": [],
                            },
                            {
                                "id": 6,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220314556",
                                "updated_at": "1681220314556",
                                "variant_ids": [],
                            },
                            {
                                "id": 7,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220640410",
                                "updated_at": "1681220640410",
                                "variant_ids": [],
                            },
                            {
                                "id": 8,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220661777",
                                "updated_at": "1681220661777",
                                "variant_ids": [],
                            },
                            {
                                "id": 9,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220712222",
                                "updated_at": "1681220712222",
                                "variant_ids": [],
                            },
                            {
                                "id": 10,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221193876",
                                "updated_at": "1681221193876",
                                "variant_ids": [],
                            },
                            {
                                "id": 11,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221219918",
                                "updated_at": "1681221219918",
                                "variant_ids": [],
                            },
                            {
                                "id": 12,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221294025",
                                "updated_at": "1681221294025",
                                "variant_ids": [],
                            },
                            {
                                "id": 13,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221300756",
                                "updated_at": "1681221300756",
                                "variant_ids": [],
                            },
                            {
                                "id": 14,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221455559",
                                "updated_at": "1681221455559",
                                "variant_ids": [],
                            },
                            {
                                "id": 16,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221525855",
                                "updated_at": "1681221525855",
                                "variant_ids": [],
                            }
                        ],
                        "image": {
                            "id": 1,
                            "product_id": 1,
                            "is_default": true,
                            "position": 1,
                            "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                            "width": 2820,
                            "height": 2400,
                            "alt": "",
                            "created_at": "1681219466084",
                            "updated_at": "1681219466084",
                        },
                        "variants": [
                            {
                                "id": 5,
                                "product_id": 1,
                                "image_id": 1,
                                "position": 1,
                                "price": 99,
                                "compare_at_price": 99,
                                "grams": 0,
                                "requires_shipping": true,
                                "sku": "SKU#LF83UERR",
                                "title": "color",
                                "created_at": "1681390906000",
                                "updated_at": "1681390906000",
                                "weight": 0,
                                "weight_unit": "gram",
                                "options": [
                                    {
                                        "id": 3,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    },
                                    {
                                        "id": 4,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    }
                                ],
                                "__typename": "ProductVariant"
                            }
                        ],
                        "shipping_rate": {
                            "id": 1,
                            "product_id": 1,
                            "title": "Standart shipping",
                            "price": 0,
                            "compare_at_price": 0,
                            "__typename": "ShippingRate"
                        },
                        "__typename": "Product"
                    },
                    "__typename": "CartLine"
                },
                {
                    "id": 3,
                    "cart_id": 136,
                    "product_id": 1,
                    "variant_id": 5,
                    "variant_option_id": 3,
                    "quantity": 1,
                    "product": {
                        "id": 1,
                        "title": "HomePod",
                        "published_at": null,
                        "tags": "music, electronics",
                        "metafields_global_title_tag": "",
                        "metafields_global_description_tag": "",
                        "seo_description": "",
                        "seo_title": "",
                        "created_at": "2023-04-11T12:48:48.020Z",
                        "updated_at": "2023-04-11T12:48:48.020Z",
                        "status": "active",
                        "images": [
                            {
                                "id": 1,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219466084",
                                "updated_at": "1681219466084",
                                "variant_ids": [
                                    5
                                ],
                            },
                            {
                                "id": 2,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219647379",
                                "updated_at": "1681219647379",
                                "variant_ids": [],
                            },
                            {
                                "id": 3,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151541",
                                "updated_at": "1681220151541",
                                "variant_ids": [],
                            },
                            {
                                "id": 4,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151792",
                                "updated_at": "1681220151792",
                                "variant_ids": [],
                            },
                            {
                                "id": 5,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220235065",
                                "updated_at": "1681220235065",
                                "variant_ids": [],
                            },
                            {
                                "id": 6,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220314556",
                                "updated_at": "1681220314556",
                                "variant_ids": [],
                            },
                            {
                                "id": 7,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220640410",
                                "updated_at": "1681220640410",
                                "variant_ids": [],
                            },
                            {
                                "id": 8,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220661777",
                                "updated_at": "1681220661777",
                                "variant_ids": [],
                            },
                            {
                                "id": 9,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220712222",
                                "updated_at": "1681220712222",
                                "variant_ids": [],
                            },
                            {
                                "id": 10,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221193876",
                                "updated_at": "1681221193876",
                                "variant_ids": [],
                            },
                            {
                                "id": 11,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221219918",
                                "updated_at": "1681221219918",
                                "variant_ids": [],
                            },
                            {
                                "id": 12,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221294025",
                                "updated_at": "1681221294025",
                                "variant_ids": [],
                            },
                            {
                                "id": 13,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221300756",
                                "updated_at": "1681221300756",
                                "variant_ids": [],
                            },
                            {
                                "id": 14,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221455559",
                                "updated_at": "1681221455559",
                                "variant_ids": [],
                            },
                            {
                                "id": 16,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221525855",
                                "updated_at": "1681221525855",
                                "variant_ids": [],
                            }
                        ],
                        "image": {
                            "id": 1,
                            "product_id": 1,
                            "is_default": true,
                            "position": 1,
                            "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                            "width": 2820,
                            "height": 2400,
                            "alt": "",
                            "created_at": "1681219466084",
                            "updated_at": "1681219466084",
                        },
                        "variants": [
                            {
                                "id": 5,
                                "product_id": 1,
                                "image_id": 1,
                                "position": 1,
                                "price": 99,
                                "compare_at_price": 99,
                                "grams": 0,
                                "requires_shipping": true,
                                "sku": "SKU#LF83UERR",
                                "title": "color",
                                "created_at": "1681390906000",
                                "updated_at": "1681390906000",
                                "weight": 0,
                                "weight_unit": 'g',
                                "options": [
                                    {
                                        "id": 3,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    },
                                    {
                                        "id": 4,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    }
                                ],
                                "__typename": "ProductVariant"
                            }
                        ],
                        "shipping_rate": {
                            "id": 1,
                            "product_id": 1,
                            "title": "Standart shipping",
                            "price": 0,
                            "compare_at_price": 0,
                        },
                        "__typename": "Product"
                    },
                    "__typename": "CartLine"
                },
                {
                    "id": 4,
                    "cart_id": 136,
                    "product_id": 1,
                    "variant_id": 5,
                    "variant_option_id": 4,
                    "quantity": 1,
                    "product": {
                        "id": 1,
                        "title": "HomePod",
                        "published_at": null,
                        "tags": "music, electronics",
                        "metafields_global_title_tag": "",
                        "metafields_global_description_tag": "",
                        "seo_description": "",
                        "seo_title": "",
                        "created_at": "2023-04-11T12:48:48.020Z",
                        "updated_at": "2023-04-11T12:48:48.020Z",
                        "status": "active",
                        "images": [
                            {
                                "id": 1,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219466084",
                                "updated_at": "1681219466084",
                                "variant_ids": [
                                    5
                                ],
                            },
                            {
                                "id": 2,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219647379",
                                "updated_at": "1681219647379",
                                "variant_ids": [],
                            },
                            {
                                "id": 3,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151541",
                                "updated_at": "1681220151541",
                                "variant_ids": [],
                            },
                            {
                                "id": 4,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151792",
                                "updated_at": "1681220151792",
                                "variant_ids": [],
                            },
                            {
                                "id": 5,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220235065",
                                "updated_at": "1681220235065",
                                "variant_ids": [],
                            },
                            {
                                "id": 6,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220314556",
                                "updated_at": "1681220314556",
                                "variant_ids": [],
                            },
                            {
                                "id": 7,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220640410",
                                "updated_at": "1681220640410",
                                "variant_ids": [],
                            },
                            {
                                "id": 8,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220661777",
                                "updated_at": "1681220661777",
                                "variant_ids": [],
                            },
                            {
                                "id": 9,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220712222",
                                "updated_at": "1681220712222",
                                "variant_ids": [],
                            },
                            {
                                "id": 10,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221193876",
                                "updated_at": "1681221193876",
                                "variant_ids": [],
                            },
                            {
                                "id": 11,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221219918",
                                "updated_at": "1681221219918",
                                "variant_ids": [],
                            },
                            {
                                "id": 12,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221294025",
                                "updated_at": "1681221294025",
                                "variant_ids": [],
                            },
                            {
                                "id": 13,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221300756",
                                "updated_at": "1681221300756",
                                "variant_ids": [],
                            },
                            {
                                "id": 14,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221455559",
                                "updated_at": "1681221455559",
                                "variant_ids": [],
                            },
                            {
                                "id": 16,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221525855",
                                "updated_at": "1681221525855",
                                "variant_ids": [],
                            }
                        ],
                        "image": {
                            "id": 1,
                            "product_id": 1,
                            "is_default": true,
                            "position": 1,
                            "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                            "width": 2820,
                            "height": 2400,
                            "alt": "",
                            "created_at": "1681219466084",
                            "updated_at": "1681219466084",
                        },
                        "variants": [
                            {
                                "id": 5,
                                "product_id": 1,
                                "image_id": 1,
                                "position": 1,
                                "price": 99,
                                "compare_at_price": 99,
                                "grams": 0,
                                "requires_shipping": true,
                                "sku": "SKU#LF83UERR",
                                "title": "color",
                                "created_at": "1681390906000",
                                "updated_at": "1681390906000",
                                "weight": 0,
                                "weight_unit": "gram",
                                "options": [
                                    {
                                        "id": 3,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    },
                                    {
                                        "id": 4,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    }
                                ],
                                "__typename": "ProductVariant"
                            }
                        ],
                        "shipping_rate": {
                            "id": 1,
                            "product_id": 1,
                            "title": "Standart shipping",
                            "price": 0,
                            "compare_at_price": 0,
                            "__typename": "ShippingRate"
                        },
                        "__typename": "Product"
                    },
                    "__typename": "CartLine"
                },
                {
                    "id": 5,
                    "cart_id": 136,
                    "product_id": 1,
                    "variant_id": 5,
                    "variant_option_id": 3,
                    "quantity": 1,
                    "product": {
                        "id": 1,
                        "title": "HomePod",
                        "published_at": null,
                        "tags": "music, electronics",
                        "metafields_global_title_tag": "",
                        "metafields_global_description_tag": "",
                        "seo_description": "",
                        "seo_title": "",
                        "created_at": "2023-04-11T12:48:48.020Z",
                        "updated_at": "2023-04-11T12:48:48.020Z",
                        "status": "active",
                        "images": [
                            {
                                "id": 1,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219466084",
                                "updated_at": "1681219466084",
                                "variant_ids": [
                                    5
                                ],
                            },
                            {
                                "id": 2,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219647379",
                                "updated_at": "1681219647379",
                                "variant_ids": [],
                            },
                            {
                                "id": 3,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151541",
                                "updated_at": "1681220151541",
                                "variant_ids": [],
                            },
                            {
                                "id": 4,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151792",
                                "updated_at": "1681220151792",
                                "variant_ids": [],
                            },
                            {
                                "id": 5,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220235065",
                                "updated_at": "1681220235065",
                                "variant_ids": [],
                            },
                            {
                                "id": 6,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220314556",
                                "updated_at": "1681220314556",
                                "variant_ids": [],
                            },
                            {
                                "id": 7,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220640410",
                                "updated_at": "1681220640410",
                                "variant_ids": [],
                            },
                            {
                                "id": 8,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220661777",
                                "updated_at": "1681220661777",
                                "variant_ids": [],
                            },
                            {
                                "id": 9,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220712222",
                                "updated_at": "1681220712222",
                                "variant_ids": [],
                            },
                            {
                                "id": 10,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221193876",
                                "updated_at": "1681221193876",
                                "variant_ids": [],
                            },
                            {
                                "id": 11,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221219918",
                                "updated_at": "1681221219918",
                                "variant_ids": [],
                            },
                            {
                                "id": 12,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221294025",
                                "updated_at": "1681221294025",
                                "variant_ids": [],
                            },
                            {
                                "id": 13,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221300756",
                                "updated_at": "1681221300756",
                                "variant_ids": [],
                            },
                            {
                                "id": 14,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221455559",
                                "updated_at": "1681221455559",
                                "variant_ids": [],
                            },
                            {
                                "id": 16,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221525855",
                                "updated_at": "1681221525855",
                                "variant_ids": [],
                            }
                        ],
                        "image": {
                            "id": 1,
                            "product_id": 1,
                            "is_default": true,
                            "position": 1,
                            "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                            "width": 2820,
                            "height": 2400,
                            "alt": "",
                            "created_at": "1681219466084",
                            "updated_at": "1681219466084",
                        },
                        "variants": [
                            {
                                "id": 5,
                                "product_id": 1,
                                "image_id": 1,
                                "position": 1,
                                "price": 99,
                                "compare_at_price": 99,
                                "grams": 0,
                                "requires_shipping": true,
                                "sku": "SKU#LF83UERR",
                                "title": "color",
                                "created_at": "1681390906000",
                                "updated_at": "1681390906000",
                                "weight": 0,
                                "weight_unit": "gram",
                                "options": [
                                    {
                                        "id": 3,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    },
                                    {
                                        "id": 4,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    }
                                ],
                                "__typename": "ProductVariant"
                            }
                        ],
                        "shipping_rate": {
                            "id": 1,
                            "product_id": 1,
                            "title": "Standart shipping",
                            "price": 0,
                            "compare_at_price": 0,
                            "__typename": "ShippingRate"
                        },
                        "__typename": "Product"
                    },
                    "__typename": "CartLine"
                },
                {
                    "id": 6,
                    "cart_id": 136,
                    "product_id": 1,
                    "variant_id": 5,
                    "variant_option_id": 3,
                    "quantity": 1,
                    "product": {
                        "id": 1,
                        "title": "HomePod",
                        "published_at": null,
                        "tags": "music, electronics",
                        "metafields_global_title_tag": "",
                        "metafields_global_description_tag": "",
                        "seo_description": "",
                        "seo_title": "",
                        "created_at": "2023-04-11T12:48:48.020Z",
                        "updated_at": "2023-04-11T12:48:48.020Z",
                        "status": "active",
                        "images": [
                            {
                                "id": 1,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219466084",
                                "updated_at": "1681219466084",
                                "variant_ids": [
                                    5
                                ],
                            },
                            {
                                "id": 2,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681219647379",
                                "updated_at": "1681219647379",
                                "variant_ids": [],
                            },
                            {
                                "id": 3,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151541",
                                "updated_at": "1681220151541",
                                "variant_ids": [],
                            },
                            {
                                "id": 4,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220151792",
                                "updated_at": "1681220151792",
                                "variant_ids": [],
                            },
                            {
                                "id": 5,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220235065",
                                "updated_at": "1681220235065",
                                "variant_ids": [],
                            },
                            {
                                "id": 6,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220314556",
                                "updated_at": "1681220314556",
                                "variant_ids": [],
                            },
                            {
                                "id": 7,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220640410",
                                "updated_at": "1681220640410",
                                "variant_ids": [],
                            },
                            {
                                "id": 8,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220661777",
                                "updated_at": "1681220661777",
                                "variant_ids": [],
                            },
                            {
                                "id": 9,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681220712222",
                                "updated_at": "1681220712222",
                                "variant_ids": [],
                            },
                            {
                                "id": 10,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221193876",
                                "updated_at": "1681221193876",
                                "variant_ids": [],
                            },
                            {
                                "id": 11,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221219918",
                                "updated_at": "1681221219918",
                                "variant_ids": [],
                            },
                            {
                                "id": 12,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221294025",
                                "updated_at": "1681221294025",
                                "variant_ids": [],
                            },
                            {
                                "id": 13,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221300756",
                                "updated_at": "1681221300756",
                                "variant_ids": [],
                            },
                            {
                                "id": 14,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221455559",
                                "updated_at": "1681221455559",
                                "variant_ids": [],
                            },
                            {
                                "id": 16,
                                "product_id": 1,
                                "is_default": true,
                                "position": 1,
                                "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                                "width": 2820,
                                "height": 2400,
                                "alt": "",
                                "created_at": "1681221525855",
                                "updated_at": "1681221525855",
                                "variant_ids": [],
                            }
                        ],
                        "image": {
                            "id": 1,
                            "product_id": 1,
                            "is_default": true,
                            "position": 1,
                            "src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-202210-gallery-1?wid=2820&hei=2400&fmt=jpeg&qlt=90&.v=1669944430181",
                            "width": 2820,
                            "height": 2400,
                            "alt": "",
                            "created_at": "1681219466084",
                            "updated_at": "1681219466084",
                        },
                        "variants": [
                            {
                                "id": 5,
                                "product_id": 1,
                                "image_id": 1,
                                "position": 1,
                                "price": 99,
                                "compare_at_price": 99,
                                "grams": 0,
                                "requires_shipping": true,
                                "sku": "SKU#LF83UERR",
                                "title": "color",
                                "created_at": "1681390906000",
                                "updated_at": "1681390906000",
                                "weight": 0,
                                "weight_unit": "gram",
                                "options": [
                                    {
                                        "id": 3,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    },
                                    {
                                        "id": 4,
                                        "product_id": 1,
                                        "variant_id": 5,
                                        "name": "White",
                                        "value": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/homepod-finish-white-202210?wid=306&amp;hei=306&amp;fmt=png-alpha&amp;.v=1669944382943",
                                        "quantity_available": 10,
                                        "note": "New",
                                        "__typename": "ProductVariantOption"
                                    }
                                ],
                                "__typename": "ProductVariant"
                            }
                        ],
                        "shipping_rate": {
                            "id": 1,
                            "product_id": 1,
                            "title": "Standart shipping",
                            "price": 0,
                            "compare_at_price": 0,
                            "__typename": "ShippingRate"
                        },
                        "__typename": "Product"
                    },
                    "__typename": "CartLine"
                }
            ],
            "__typename": "Cart"
        } as any as ICartListing;
        
    }
    const cart: ICartListing = {
        ..._cart,
        total_quantity: 0,
        cost:  {
            total: 0,
            subtotal: 0,
            checkout_charge: 0,
            total_duty: 0,
            total_tax: 0,
        }
    }

    let productIdsFound: number[] = [];

    cart.line_items = cart.line_items.map(item=>{
        cart.total_quantity += 1;
        let variant = item.product.variants.filter(variant=>variant.id === item.variant_id)[0] || null;
        item = {
            ...item,
            cost: {
                subtotal_amount: 0,
                total_amount: 0
            }
        }

        if(variant) {
            const itemCostSubtotal = variant.price * item.quantity;
            item.cost.subtotal_amount = itemCostSubtotal;
            item.cost.total_amount = itemCostSubtotal;

            cart.cost.subtotal += item.cost.total_amount;
        }

        if(!productIdsFound.includes(item.product_id)){
            cart.cost.total_duty += item.product.shipping_rate.price
            productIdsFound.push(item.product_id)
        }

        return item;
    })

    cart.cost.total = cart.cost.subtotal + cart.cost.total_duty + cart.cost.total_tax;
    cart.cost.checkout_charge = cart.cost.total;

    return cart;
}